### PR TITLE
Fixing FactoryGirl depracation warning

### PR DESCRIPTION
**Pull request by ben-goldberg**
Issue #4 

This PR updates the version of `FactoryGirl` and updates the `create_record` method to lookup a factory by symbol instead of class name. This is because `FactoryGirl` complains that looking up a factory by class name is deprecated.

@kevgo

### CODE REVIEW

**Comment by ben-goldberg** [comment]
Not sure why the tests are failing on CircleCI? They're passing locally. Here's the error message:

```
bundle exec rake

bundle exec rubocop
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/bin/bundle:22:in `load': cannot load such file -- /home/ubuntu/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.9.5/lib/gems/bundler-1.9.5/bin/bundle (LoadError)
    from /home/ubuntu/.rvm/gems/ruby-2.2.3@global/bin/bundle:22:in `<main>'
rake aborted!
Command failed with status (1): [bundle exec rubocop...]
/home/ubuntu/active_cucumber/Rakefile:23:in `block in <top (required)>'
Tasks: TOP => default => lint => lint:ruby
(See full trace by running task with --trace)

bundle exec rake returned exit code 1
```

**Comment by ben-goldberg** [comment]
bump!

**Comment by kevgo** [comment]
Sorry for the delay @ben-goldberg, I wasn't letting you hanging. I was investigating the breakage on Circle. It didn't make any sense at all, and it seems it was a configuration error on the Circle Linux image. That is fixed now, and everything works! Sometimes all you gotta do is wait a day and problems dissolve by themselves!  :)

Thanks for fixing this, 🚀

**Comment by ben-goldberg** [comment]
:+1:

**Pull request merged**
